backend:
  name: git-gateway
  branch: main
  publish_mode: editorial_workflow

media_folder: "images/uploads"  # where uploaded images will be stored in the repo
public_folder: "/images/uploads"  # how those images are accessed in the site

collections:
  - name: "blog"
    label: "Blog"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }
