backend:
  name: github
  repo: arukode/my-portfolio-site
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: auth
  site_domain: arukode.github.io
  open_authoring: true

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }
